app/models.py
from flask_login import UserMixin
from werkzeug.security import generate_password_hash
from flask_sqlalchemy import SQLAlchemy


db = SQLAlchemy()

class Users(db.Model, UserMixin):
    id = db.Column(db.Integer(), primary_key=True, nullable=False, unique=True)
    last_name = db.Column(db.String(length=30), nullable=False)
    first_name = db.Column(db.String(length=30), nullable=False)
    email_address = db.Column(db.String(length=50),nullable=False, unique=True)
    password_hash = db.Column(db.String(length=200), nullable=False)
    is_admin = db.Column(db.Boolean(), nullable=False, default=False)
    
    def json(self):
        return {
            'id': self.id, 
            'last_name': self.last_name, 
            'first_name': self.first_name,
            'email_address': self.email_address,
            'is_admin': self.is_admin
            }

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

def init_db():
    db.create_all()
    Users(last_name="HADDOU", first_name= "ayoub1", email_address= "ayoub1@gmail.com", 
            password_hash= generate_password_hash("1234", method='sha256'), is_admin=True).save_to_db()
    

app/forms.py
from flask_wtf import FlaskForm

from wtforms import PasswordField, EmailField, SubmitField, StringField
from wtforms.validators import DataRequired

class Login(FlaskForm):
    """[Form to login]
    """
    email = EmailField(label="Adresse mail:", validators=[DataRequired()])
    password = PasswordField(label="Mot de passe:",
                             validators=[DataRequired()])
    submit = SubmitField(label="Login")

class AddUser(FlaskForm):
    """[Form to add user]
    """
    last_name = StringField(label='Nom', validators=[DataRequired()])
    first_name = StringField(label='Prénom', validators=[DataRequired()])
    email_address = StringField(label='Email', validators=[DataRequired()])
    password_hash = PasswordField(label='Mot de passe', validators=[DataRequired()])
    password_hash2 = PasswordField(label='Confirmez votre mot de passe', validators=[DataRequired()])
    submit = SubmitField(label='Ajouter')

app/__init__.py
from flask import Flask
from flask_login import LoginManager
import os
from dotenv import load_dotenv
load_dotenv()

app = Flask(__name__)
app.config["SECRET_KEY"] = os.getenv('SECRET_KEY')
app.config["WTF_CSRF_SECRET_KEY"] = os.getenv('WTF_CSRF_SECRET_KEY')
app.config["SQLALCHEMY_DATABASE_URI"] = os.getenv('SQLALCHEMY_DATABASE_URI')
app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

from .routes import main
app.register_blueprint(main)

from .models import Users, db, init_db
db.init_app(app)

login_manager = LoginManager(app)
login_manager.login_view = "login"
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return Users.query.get(int(user_id))

if os.path.isfile("app/database.db"):
    pass
else:
    app.app_context().push()
    init_db()
    

app/routes.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flask_login import login_manager
from .forms import AddUser, Login 
from .models import Users 
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, logout_user, login_required, current_user
import requests

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def homepage():
    return render_template("home.html")

@main.route('/add_user', methods= ['GET', 'POST'])
def add_user():
    form = AddUser()
    if form.validate_on_submit():
        if form.password_hash.data == form.password_hash2.data:
            check = Users.query.filter_by(email_address = form.email_address.data).first()
            if check : 
                flash('Email already exists', category='danger')
                requests.post(f"https://prod-07.centralus.logic.azure.com/workflows/2c29915665b34973a0223eca1ea86a66/triggers/manual/paths/invoke/{form.first_name.data}/{form.last_name.data}/{form.email_address.data}?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=ppS68I1_ePRmJqxfP4aY5wpEHKWlxCnowUPJRG1cMGY")
                return redirect(url_for('main.add_user'))
            else:
                Users(last_name = form.last_name.data, first_name = form.first_name.data, email_address = form.email_address.data, password_hash = generate_password_hash(form.password_hash.data, method='sha256')).save_to_db()
                flash('Nouvel utilisateur ajouté ', category='secondary')
                return redirect(url_for('main.login'))
        else:
            flash('Please enter same password')
    return render_template('add_user.html', form=form)

@main.route("/login", methods=["GET","POST"])
def login():
    form = Login()
    if form.validate_on_submit():
        user = Users.query.filter_by(email_address=form.email.data).first()
        if user and check_password_hash(user.password_hash, form.password.data):
            login_user(user)
            flash("Logged in with success", category="success")
            return redirect(url_for('main.homepage'))
        else:
            flash("Mail address or password invalid", category="danger")
    return render_template('login.html', form=form)

@main.route('/logout')
def logout_page():
    logout_user()
    flash('Vous êtes correctement déconnecté',category="success")
    return redirect(url_for('main.login'))

def compute_item(x):
    return x*2 

app/templates/add_user.html
{% extends "base.html" %}
{% block title %}
Ajout utilisateur
{% endblock %}
{% block content%}

<div class='main1'>
    <h1>Nouvel utilisateur</h1>
    <form method="POST" class="main1">
        {{ form.hidden_tag() }}

        {{ form.last_name.label }}
        {{ form.last_name(size=32, class="form-control") }}
        <br>

        {{ form.first_name.label }}
        {{ form.first_name(class="form-control") }}
        <br>

        {{ form.email_address.label }}
        {{ form.email_address(size=32, class="form-control") }}
        <br>

        {{ form.password_hash.label }}
        {{ form.password_hash(class="form-control") }}
        <br>


        {{ form.password_hash2.label }}
        {{ form.password_hash2(class="form-control") }}
        <br>

        {{ form.submit(class="btn btn-lg btn-dark mt-4 d-block",id="button") }}
    </form>
</div>


<div class='main2'>
    <h1>Mot de pass oublié </h1>
    <form method="POST" class="main1">
        {{ form.hidden_tag() }}

        {{ form.last_name.label }}
        {{ form.last_name(size=32, class="form-control") }}
        <br>

        {{ form.first_name.label }}
        {{ form.first_name(class="form-control") }}
        <br>

        {{ form.email_address.label }}
        {{ form.email_address(size=32, class="form-control") }}
        <br>


        {{ form.submit(class="btn btn-lg btn-dark mt-4 d-block",id="button") }}
    </form>
</div>
{% endblock %}

app/templates/base.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap pour flask login -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous" />
  <!-- CSS -->
  <link rel="stylesheet" href="/static/css/grid.css">

  <title>
    {% block title %}
    {% endblock %}
  </title>

</head>

<body>
  <nav>
    <ul>
      <a aria-current="page" href="{{ url_for('main.homepage') }}">Home</a>
      {% if current_user.is_authenticated %}
      <a class="nav-link" href="{{ url_for('main.logout_page') }}">Log out</a>
      <a class="nav-link">Welcome {{ current_user.first_name }}</a>
      {% else %}
      <a class="nav-link" href="{{ url_for('main.login') }}">Log in</a>
      <a class="nav-link" href="{{ url_for('main.add_user') }}">Create an account</a>
      {% endif %}
    </ul>
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category,message in messages %}
    <div class="alert alert-{{ category }} alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
  </nav>


  {% block content %}
  {% endblock %}


  <div class="foot">
    <div>
      <h5 class="align center">Contact</h5>
    </div>
  </div>

</html>

app/templates/home.html
{% extends "base.html" %}
{% block content %}

<div class="main1">
  <h1> Welcome to my website project</h1>
  <p>
    Content is coming soon ...
  </p>
</div>

<div class="main2">
  <h1> Welcome to my website project</h1>
  <p>
    Content is coming soon ...
  </p>
</div>

{% endblock %}

app/templates/login.html
{% extends "base.html" %}
{% block title %}
Login
{% endblock %}

{% block content %}

<div class="main2">
  <h1>Log in</h1>

  <div class="rowflex">

    <form method="POST" class="form-register">
      <div>{{ form.hidden_tag() }}</div>
      <div class="form-inside">
        <div class="email">
          <div class="email-label">Email:</div>
          {{form.email(placeholder="exemple@exemple.com",
          class="form-control")}}
        </div>
        <div class="password">
          <div class="password-label">Password:</div>
          {{form.password(placeholder="***********", class="form-control")}}
        </div>

        <div class="rowflex">
          <div class="element">{{ form.submit(class="btn bouton", id="button")}}</div>
          <div class="element"><a href="{{ url_for('main.add_user') }}">Register</a></div>
        </div>
      </div>
    </form>

  </div>
</div>

<div class="main1">
  <h1> Welwom to my website project</h1>
  <p>
    Content is coming soon ...
  </p>
</div>


{% endblock %}